import React from 'react';
import Head from 'next/head'



class Home extends React.Component<{}> {   

  render(){
    return (
      <>
        <Head>
          <title>Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>        
        
      </>
    );
  }
}

export default Home;